### ISSUE TITLE
COM Interop

### ISSUE THREAD

**Issue by kczx3** [schoetbi/XPTable#22]
I am attempting to use this control through the Common Language Runtime via AutoHotkey.  I am able to set values and create a GUI with the control in it.  I am to the point of attempting to handle events now.  I began with the ToolTips.  Simply enabling them via table.EnableToolTips = True did not produce the default tooltip if the cell isn't showing all of the text.  I am using some code created by the current developer of AutoHotkey to try and handle the event but am having difficulties.  Here is the code -> [https://autohotkey.com/boards/viewtopic.php?f=6&t=4633#p26497](url).

I am getting an error when my mouse hovers over a cell that shows the following,

`************** Exception Text **************
System.InvalidOperationException: This type has a ComVisible(false) parent in its hierarchy, therefore QueryInterface calls for IDispatch or class interfaces are disallowed.
   at System.StubHelpers.MngdSafeArrayMarshaler.ConvertContentsToNative(IntPtr pMarshalState, Object& pManagedHome, IntPtr pNativeHome, Object pOriginalManaged)
   at XPTable.Models.Table.OnCellToolTipPopup(CellToolTipEventArgs e)
   at XPTable.Renderers.CellRenderer.OnMouseEnter(CellMouseEventArgs e)
   at XPTable.Models.Table.OnCellMouseEnter(CellMouseEventArgs e)
   at XPTable.Models.Table.RaiseCellMouseEnter(CellPos cellPos)
   at XPTable.Models.Table.OnMouseMove(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseMove(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)`

I'm having trouble determining what may be the problem and am curious if this assembly is not ComVisible.  From my research, I believe that all assemblies are visible unless ComVisible is set to false.  Hoping you can provide some insight.  Thanks

**Comment by schoetbi** [comment]
I have no experience with autohotkey. But from what I have read .net classes should be comVisible by default. What changes to XP table do you suggest?
Tobias

**Comment by kczx3** [comment]
The problem is I have no experience with .Net either.  Other than what I've read investigating this current issue I'm having.  I tried setting ComVisible to True on the assembly and including System.Runtime.InteropServices but that did not fix the issue.  At this point I have no suggestions to make.  Just thought I'd pose the question.... figured it couldn't hurt.
