### ISSUE TITLE
NullreferenceException at XPTable.Models.Table.OnMouseMove

### ISSUE THREAD

**Issue by schoetbi** [schoetbi/XPTable#33]
XPTable= a7dbeddfc8a24d9fc634cb584c3be0183762fb20

```
at XPTable.Models.Table.OnMouseMove(MouseEventArgs e) in S:\xptable\xptable_git\Models\Table.cs:line 7402
at System.Windows.Forms.Control.WmMouseMove(Message& m)
at System.Windows.Forms.Control.WndProc(Message& m)
at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by schoetbi** [comment]
fixed with 783252da
